version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: mern_template_server
    container_name: mern_template_server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
    env_file: ./server/.env
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: mern_template_client
    container_name: mern_template_client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
